# Generated by Django 4.2.3 on 2023-07-26 18:16

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(null=True, upload_to=account.models.CustomUser.image_upload),
        ),
    ]
